import type { Metadata, Viewport } from "next";
import "./styles/globals.css";

import Navbar from "@/components/navbar";
import LoadingSpinner from "@/components/LoadingSpinner";
import Footer from "@/components/Footer";
import CustomCursor from "@/components/CustomCursor";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="cursor-none">
        <CustomCursor />
        <LoadingSpinner />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
